<a href="https://colab.research.google.com/github/shubhamkumar62092/placement-prediction/blob/main/placementprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import pickle
import numpy as np
import sklearn

In [2]:
from sys import version
print("numpy",np.__version__)
print("pandas",pd.__version__)
print("sklearn" , sklearn.__version__)

numpy 2.0.2
pandas 2.2.2
sklearn 1.6.1

In [3]:
file_path ='/content/data.csv'
data = pd.read_csv(file_path)
data.head()

   StudentID  CGPA  SSC_Marks  HSC_Marks PlacementStatus
0          1   7.5         61         79       NotPlaced
1          2   8.9         78         82          Placed
2          3   7.3         79         80       NotPlaced
3          4   7.5         81         80          Placed
4          5   8.3         74         88          Placed

In [4]:
!python --version

Python 3.12.13

In [5]:
mapping = {'Placed': 1, 'NotPlaced': 0}
data['PlacementStatus'] = data['PlacementStatus'].map(mapping)
data.head()

   StudentID  CGPA  SSC_Marks  HSC_Marks  PlacementStatus
0          1   7.5         61         79                0
1          2   8.9         78         82                1
2          3   7.3         79         80                0
3          4   7.5         81         80                1
4          5   8.3         74         88                1

In [6]:
x = data.drop(columns = ['StudentID','PlacementStatus'], axis=1)
y = data['PlacementStatus']

x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [7]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [8]:
from sklearn.model_selection import GridSearchCV
rf=RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5,n_jobs=-1,verbose=2)
grid_search.fit(x_train, y_train)
best_rf = grid_search.best_estimator_

Fitting 5 folds for each of 81 candidates, totalling 405 fits

In [9]:
y_pred = best_rf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80      1172
           1       0.72      0.71      0.71       828

    accuracy                           0.76      2000
   macro avg       0.76      0.76      0.76      2000
weighted avg       0.76      0.76      0.76      2000

In [10]:
with open('model.pkl', 'wb') as file:
    pickle.dump(best_rf, file)